name = "ClassificationOfSubgroups"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ClassificationOfSubgroups"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
[[lean_lib]]
name = "ClassificationOfSubgroups"


# name = "myprojectname"
# defaultTargets = ["textbook"]

# [[require]]
# name = "verso"
# git = "https://github.com/leanprover/verso"
# rev = "main"

# [[lean_lib]]
# name = "DemoTextbook"

# [[lean_exe]]
# name = "textbook"
# root = "DemoTextbookMain"
